GET http://localhost:4000/users

###
GET http://localhost:4000/user/63c3b236679194b073d980a8


###
POST http://localhost:4000/register
Content-Type:application/json

{
  "name": "Govind",
  "email": "govind@golok.om",
  "password": "hhh4hhhhh",
  "mobile":"1234567890",
  "location": "Delhi",
  "gender":"female"
}

###
PUT http://localhost:4000/update-details/63c3b083679194b073d980a1
Content-Type:application/json

{
  "name": "RadheKrishna"
}

###

DELETE http://localhost:4000/remove-user/63c3b083679194b073d980a1

###

GET http://localhost:4000/trail