GET http://localhost:4000/users

###
GET http://localhost:4000/user/63c251f918d80f3bcd776575


###
POST http://localhost:4000/register
Content-Type:application/json

{
  "name": "Hare",
  "email": "alksjfdl@golok.om",
  "password": "hhh4hhhhh",
  "mobile":"98235793485",
  "location": "Delhi",
  "gender":"female"
}

###
PUT http://localhost:4000/update-details/63c251f918d80f3bcd776575
Content-Type:application/json

{
  "mobile": "1111111111"
}

###

DELETE http://localhost:4000/remove-user/63c251f918d80f3bcd776575

###

GET http://localhost:4000/trail